import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import BlogLanding from "components/BlogLanding";
import BlogPostPage from "components/BlogPostPage";
import BlogSection from "components/BlogSection";
import Footer from "components/Footer";
import Hero from "components/Hero";
import MouseCircle from "components/MouseCircle";
import NavBar from "components/NavBar";
import OpenSource from "components/OpenSource";
import Project from "components/Project";
import Publications from "components/Publications";
import Resources from "components/Resources";
import Toolbox from "components/Toolbox";
import Head from "next/head";
import Image from "next/image";
import TimeLine from "../../components/TimeLine";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="">
				{/* <NavBar /> */}
				{/* <MouseCircle /> */}
				{/* <Hero /> */}

				<Toolbox />
				{/* <TimeLine /> */}
				<Project />
				<Publications />
				{/* <BlogPostPage /> */}
				{/* <BlogLanding /> */}
				<BlogSection />
				<Resources />
				<OpenSource />
				{/* <Footer /> */}
			</div>
		</>
	);
}
